### ISSUE TITLE
Creación de APIs CRUD y MID para el nuevo resoluciones.

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_crud_api#9]
Registrar la creación y ajuste de las APIs CRUD y MID asociadas al nuevo resoluciones.

**Criterios de aceptación**

- [x] Creación y ajustes de API CRUD
- [x] Creación y ajustes de API MID

**Comment by jupmorenor** [comment]
Se realizó creación de API CRUD a partir del modelo de datos trabajado en [udistrital/resoluciones_docentes_crud#25](https://github.com/udistrital/resoluciones_docentes_crud/issues/25) incluyendo todos los componentes requeridos por los lineamientos de la OAS: migrations, refactor, variables de entorno, readme actualizado, archivo sonar y drone; y se ha subido al repositorio correspondiente: https://github.com/udistrital/resoluciones_crud_v2

![image](https://user-images.githubusercontent.com/11802554/140073570-0a748537-4e67-4264-bc9b-bf91ccec1683.png)

**Comment by jupmorenor** [comment]
Igualmente se realizó creación de API MID, en este caso vacía, en esta API también se han incluido todos los componentes requeridos por los lineamientos de la OAS: variables de entorno, readme actualizado, archivo sonar y drone; la API se ha subido al repositorio https://github.com/udistrital/resoluciones_mid_v2

![image](https://user-images.githubusercontent.com/11802554/140074010-a14b05be-20e0-46ad-a778-932a36a10e38.png)

**Comment by jupmorenor** [comment]
Se ha actualizado la API CRUD con los últimos cambios realizados al modelo de datos expuestos en [udistrital/resoluciones_docentes_crud#25](https://github.com/udistrital/resoluciones_docentes_crud/issues/25)
